In [12]:
import numpy as np
import pandas as pd

In [13]:
df_GEI = pd.read_csv(r"C:\Users\ttjrb\OneDrive\Desktop\University Important\PROJECTS\NBA data analyzed\database\GEI_scraped.csv")
df_metrics = pd.read_csv(r"/database/Ei_metrics_beforeGEI.csv")

In [16]:
def match_gei(row):
    matched = df_GEI[
        (df_GEI["Date"] == row["DATE"]) &
        (df_GEI["Score"].str.contains(row["TEAM1"], case=False, na=False)) &
        (df_GEI["Score"].str.contains(row["TEAM2"], case=False, na=False))
    ]
    return matched["Excitment"].mean() if not matched.empty else 0

In [22]:
df_metrics["GEI"] = df_metrics.apply(match_gei, axis=1)

In [23]:
df_metrics.head(20)

     GAME_ID TEAM1 TEAM2        DATE  PF  3PM  DUNKS  OT  CLUTCH   GEI
0   22401186   ATL   ORL  2025-04-13  23   32     16   0       0   4.9
1   22401188   BKN   NYK  2025-04-13  49   28      5   0       1   7.5
2   22401195   UTA   MIN  2025-04-13  31   29     11   0       0   5.1
3   22401194   MEM   DAL  2025-04-13  28   20     19   0       0   3.2
4   22401196   OKC   NOP  2025-04-13  44   16      6   0       0   3.7
5   22401200   SAC   PHX  2025-04-13  16   29      7   0       0   5.0
6   22401192   MIL   DET  2025-04-13  36   45      5   1       1   9.1
7   22401187   BOS   CHA  2025-04-13  30   25      4   0       1   0.0
8   22401199   POR   LAL  2025-04-13  37   24     12   0       0   3.5
9   22401193   DEN   HOU  2025-04-13  37   22     13   0       0   3.2
10  22401190   WAS   MIA  2025-04-13  26   26     15   0       1   9.1
11  22401198   GSW   LAC  2025-04-13  41   29     12   1       1  10.2
12  22401191   PHI   CHI  2025-04-13  32   25     13   0       0   5.4
13  22401189   CLE   IND  2025-04-13  43   28     10   1       1   0.0
14  22401197   TOR   SAS  2025-04-13  36   25     12   0       1   6.8
15  22401184   LAC   SAC  2025-04-11  37   17      8   0       1   7.3
16  22401172   IND   ORL  2025-04-11  47   25     11   0       0   2.5
17  22401185   LAL   HOU  2025-04-11  32   37     16   0       0   3.3
18  22401171   DET   MIL  2025-04-11  36   35     12   0       1   8.0
19  22401176   CHI   WAS  2025-04-11  29   23      8   0       0   3.1

In [24]:
df_metrics[df_metrics['GEI']==0]

      GAME_ID TEAM1 TEAM2        DATE  PF  3PM  DUNKS  OT  CLUTCH  GEI
7    22401187   BOS   CHA  2025-04-13  30   25      4   0       1  0.0
13   22401189   CLE   IND  2025-04-13  43   28     10   1       1  0.0
27   22401177   NOP   MIA  2025-04-11  29   34     12   0       0  0.0
43   22401157   PHI   WAS  2025-04-09  45   26      9   0       0  0.0
93   22401104   CHA   IND  2025-04-02  31   28      9   0       0  0.0
123  22401075   WAS   BKN  2025-03-29  38   27      7   0       1  0.0
128  22401068   BKN   LAC  2025-03-28  43   33      9   0       0  0.0
143  22401053   PHI   WAS  2025-03-26  27   32     15   0       1  0.0
356  22400847   CHA   DAL  2025-02-27  27   18      9   0       1  0.0
430  22400770   CHA   ORL  2025-02-12  27   22      5   0       0  0.0
588  22400613   PHX   BKN  2025-01-22  23   21      6   0       0  0.0
633  22400563   CHI   ATL  2025-01-15  30   19      9   0       0  0.0
662  22400546   UTA   BKN  2025-01-12  47   27      9   1       1  0.0

In [26]:
df_metrics.loc[df_metrics['GEI']==0, 'GEI']=df_metrics['GEI'].mean()
df_metrics[df_metrics['GEI']==0]

Empty DataFrame
Columns: [GAME_ID, TEAM1, TEAM2, DATE, PF, 3PM, DUNKS, OT, CLUTCH, GEI]
Index: []

In [29]:
df_metrics.to_csv("Ei_metrics_beforePerf.csv", index=False)