In [3]:
import numpy as np
from nba_api.stats.endpoints import leaguegamefinder
import pandas as pd
from nba_api.stats.endpoints import playbyplayv2

In [127]:
# get game logs from the reg season
gamefinder = leaguegamefinder.LeagueGameFinder(season_nullable='2024-25',
                                              league_id_nullable='00',
                                              season_type_nullable='Regular Season')
games = gamefinder.get_data_frames()[0]
games.tail(10)

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
2450,22024,1610612756,PHX,Phoenix Suns,0022400071,2024-10-23,PHX @ LAC,W,264,116,...,0.735,4,38,42,25,12,9,22,23,3.0
2451,22024,1610612737,ATL,Atlanta Hawks,0022400064,2024-10-23,ATL vs. BKN,W,241,120,...,0.717,12,33,45,25,12,9,16,20,4.0
2452,22024,1610612765,DET,Detroit Pistons,0022400063,2024-10-23,DET vs. IND,L,241,109,...,0.857,12,26,38,22,6,2,12,21,-6.0
2453,22024,1610612740,NOP,New Orleans Pelicans,0022400069,2024-10-23,NOP vs. CHI,W,241,123,...,0.905,7,35,42,29,15,10,11,17,12.0
2454,22024,1610612761,TOR,Toronto Raptors,0022400067,2024-10-23,TOR vs. CLE,L,240,106,...,0.759,14,24,38,25,8,6,18,24,-30.0
2455,22024,1610612741,CHI,Chicago Bulls,0022400069,2024-10-23,CHI @ NOP,L,242,111,...,0.680,9,38,47,26,4,2,21,16,-12.0
2456,22024,1610612738,BOS,Boston Celtics,0022400061,2024-10-22,BOS vs. NYK,W,240,132,...,0.875,11,29,40,33,6,3,3,15,23.0
2457,22024,1610612747,LAL,Los Angeles Lakers,0022400062,2024-10-22,LAL vs. MIN,W,240,110,...,0.840,15,31,46,22,7,8,7,22,7.0
2458,22024,1610612750,MIN,Minnesota Timberwolves,0022400062,2024-10-22,MIN @ LAL,L,239,103,...,0.741,12,35,47,17,4,1,15,22,-7.0
2459,22024,1610612752,NYK,New York Knicks,0022400061,2024-10-22,NYK @ BOS,L,241,109,...,0.750,5,29,34,20,2,3,11,12,-23.0

In [128]:
# get a list of the distinct game_ids
game_ids = games['GAME_ID'].unique().tolist()
len(game_ids)

1230

In [150]:
pbp = playbyplayv2.PlayByPlayV2(game_ids[0])
pbp = pbp.get_data_frames()[0]
pbp.tail(10)

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,...,PLAYER2_TEAM_NICKNAME,PLAYER2_TEAM_ABBREVIATION,PERSON3TYPE,PLAYER3_ID,PLAYER3_NAME,PLAYER3_TEAM_ID,PLAYER3_TEAM_CITY,PLAYER3_TEAM_NICKNAME,PLAYER3_TEAM_ABBREVIATION,VIDEO_AVAILABLE_FLAG
395,0022401186,557,1,79,4,3:03 PM,1:28,None,None,da Silva 25' 3PT Pullup Jump Shot (14 PTS),...,None,None,0,0,None,NaN,None,None,None,1
396,0022401186,558,2,101,4,3:03 PM,1:12,MISS Toppin 3' Driving Floating Jump Shot,None,Bitadze BLOCK (1 BLK),...,None,None,5,1629048,Goga Bitadze,1.610613e+09,Orlando,Magic,ORL,1
397,0022401186,560,4,0,4,3:03 PM,1:08,None,None,Black REBOUND (Off:2 Def:7),...,None,None,0,0,None,NaN,None,None,None,1
398,0022401186,561,1,6,4,3:04 PM,0:59,None,None,Howard 2' Driving Layup (16 PTS) (Black 2 AST),...,Magic,ORL,0,0,None,NaN,None,None,None,1
399,0022401186,562,2,79,4,3:04 PM,0:37,MISS Wallace 17' Pullup Jump Shot,None,None,...,None,None,0,0,None,NaN,None,None,None,1
400,0022401186,563,4,0,4,3:04 PM,0:32,Plowden REBOUND (Off:1 Def:3),None,None,...,None,None,0,0,None,NaN,None,None,None,1
401,0022401186,564,2,97,4,3:04 PM,0:32,MISS Plowden Tip Layup Shot,None,None,...,None,None,0,0,None,NaN,None,None,None,1
402,0022401186,565,4,0,4,3:04 PM,0:31,None,None,Black REBOUND (Off:2 Def:8),...,None,None,0,0,None,NaN,None,None,None,1
403,0022401186,566,5,11,4,3:04 PM,0:10,None,None,Magic Turnover: Shot Clock (T#15),...,None,None,1,0,None,NaN,None,None,None,1
404,0022401186,567,13,0,4,3:05 PM,0:00,None,End of 4th Period (3:05 PM EST),None,...,None,None,0,0,None,NaN,None,None,None,1

In [7]:
i=0
for row in pbp.itertuples(index=False):
    print(row)
    print("\n")
    i+=1
    if i ==5:
        break

Pandas(GAME_ID='0022401186', EVENTNUM=2, EVENTMSGTYPE=12, EVENTMSGACTIONTYPE=0, PERIOD=1, WCTIMESTRING='1:12 PM', PCTIMESTRING='12:00', HOMEDESCRIPTION=None, NEUTRALDESCRIPTION='Start of 1st Period (1:12 PM EST)', VISITORDESCRIPTION=None, SCORE=None, SCOREMARGIN=None, PERSON1TYPE=0, PLAYER1_ID=0, PLAYER1_NAME=None, PLAYER1_TEAM_ID=nan, PLAYER1_TEAM_CITY=None, PLAYER1_TEAM_NICKNAME=None, PLAYER1_TEAM_ABBREVIATION=None, PERSON2TYPE=0, PLAYER2_ID=0, PLAYER2_NAME=None, PLAYER2_TEAM_ID=nan, PLAYER2_TEAM_CITY=None, PLAYER2_TEAM_NICKNAME=None, PLAYER2_TEAM_ABBREVIATION=None, PERSON3TYPE=0, PLAYER3_ID=0, PLAYER3_NAME=None, PLAYER3_TEAM_ID=nan, PLAYER3_TEAM_CITY=None, PLAYER3_TEAM_NICKNAME=None, PLAYER3_TEAM_ABBREVIATION=None, VIDEO_AVAILABLE_FLAG=0)


Pandas(GAME_ID='0022401186', EVENTNUM=4, EVENTMSGTYPE=10, EVENTMSGACTIONTYPE=0, PERIOD=1, WCTIMESTRING='1:12 PM', PCTIMESTRING='12:00', HOMEDESCRIPTION='Jump Ball Barlow vs. Carter Jr.: Tip to Mann', NEUTRALDESCRIPTION=None, VISITORDESCRIPTION=None, SCORE=None, SCOREMARGIN=None, PERSON1TYPE=4, PLAYER1_ID=1631230, PLAYER1_NAME='Dominick Barlow', PLAYER1_TEAM_ID=1610612737.0, PLAYER1_TEAM_CITY='Atlanta', PLAYER1_TEAM_NICKNAME='Hawks', PLAYER1_TEAM_ABBREVIATION='ATL', PERSON2TYPE=5, PLAYER2_ID=1628976, PLAYER2_NAME='Wendell Carter Jr.', PLAYER2_TEAM_ID=1610612753.0, PLAYER2_TEAM_CITY='Orlando', PLAYER2_TEAM_NICKNAME='Magic', PLAYER2_TEAM_ABBREVIATION='ORL', PERSON3TYPE=4, PLAYER3_ID=1629611, PLAYER3_NAME='Terance Mann', PLAYER3_TEAM_ID=1610612737.0, PLAYER3_TEAM_CITY='Atlanta', PLAYER3_TEAM_NICKNAME='Hawks', PLAYER3_TEAM_ABBREVIATION='ATL', VIDEO_AVAILABLE_FLAG=1)


Pandas(GAME_ID='0022401186', EVENTNUM=7, EVENTMSGTYPE=2, EVENTMSGACTIONTYPE=63, PERIOD=1, WCTIMESTRING='1:12 PM', PCTIMESTRING='11:43', HOMEDESCRIPTION="MISS Mann 4' Fadeaway Jumper", NEUTRALDESCRIPTION=None, VISITORDESCRIPTION=None, SCORE=None, SCOREMARGIN=None, PERSON1TYPE=4, PLAYER1_ID=1629611, PLAYER1_NAME='Terance Mann', PLAYER1_TEAM_ID=1610612737.0, PLAYER1_TEAM_CITY='Atlanta', PLAYER1_TEAM_NICKNAME='Hawks', PLAYER1_TEAM_ABBREVIATION='ATL', PERSON2TYPE=0, PLAYER2_ID=0, PLAYER2_NAME=None, PLAYER2_TEAM_ID=nan, PLAYER2_TEAM_CITY=None, PLAYER2_TEAM_NICKNAME=None, PLAYER2_TEAM_ABBREVIATION=None, PERSON3TYPE=0, PLAYER3_ID=0, PLAYER3_NAME=None, PLAYER3_TEAM_ID=nan, PLAYER3_TEAM_CITY=None, PLAYER3_TEAM_NICKNAME=None, PLAYER3_TEAM_ABBREVIATION=None, VIDEO_AVAILABLE_FLAG=1)


Pandas(GAME_ID='0022401186', EVENTNUM=8, EVENTMSGTYPE=4, EVENTMSGACTIONTYPE=0, PERIOD=1, WCTIMESTRING='1:12 PM', PCTIMESTRING='11:40', HOMEDESCRIPTION=None, NEUTRALDESCRIPTION=None, VISITORDESCRIPTION='Carter Jr. REBOUND (Off:0 Def:1)', SCORE=None, SCOREMARGIN=None, PERSON1TYPE=5, PLAYER1_ID=1628976, PLAYER1_NAME='Wendell Carter Jr.', PLAYER1_TEAM_ID=1610612753.0, PLAYER1_TEAM_CITY='Orlando', PLAYER1_TEAM_NICKNAME='Magic', PLAYER1_TEAM_ABBREVIATION='ORL', PERSON2TYPE=0, PLAYER2_ID=0, PLAYER2_NAME=None, PLAYER2_TEAM_ID=nan, PLAYER2_TEAM_CITY=None, PLAYER2_TEAM_NICKNAME=None, PLAYER2_TEAM_ABBREVIATION=None, PERSON3TYPE=0, PLAYER3_ID=0, PLAYER3_NAME=None, PLAYER3_TEAM_ID=nan, PLAYER3_TEAM_CITY=None, PLAYER3_TEAM_NICKNAME=None, PLAYER3_TEAM_ABBREVIATION=None, VIDEO_AVAILABLE_FLAG=1)


Pandas(GAME_ID='0022401186', EVENTNUM=9, EVENTMSGTYPE=2, EVENTMSGACTIONTYPE=1, PERIOD=1, WCTIMESTRING='1:13 PM', PCTIMESTRING='11:23', HOMEDESCRIPTION=None, NEUTRALDESCRIPTION=None, VISITORDESCRIPTION="MISS Caldwell-Pope 25' 3PT Jump Shot", SCORE=None, SCOREMARGIN=None, PERSON1TYPE=5, PLAYER1_ID=203484, PLAYER1_NAME='Kentavious Caldwell-Pope', PLAYER1_TEAM_ID=1610612753.0, PLAYER1_TEAM_CITY='Orlando', PLAYER1_TEAM_NICKNAME='Magic', PLAYER1_TEAM_ABBREVIATION='ORL', PERSON2TYPE=0, PLAYER2_ID=0, PLAYER2_NAME=None, PLAYER2_TEAM_ID=nan, PLAYER2_TEAM_CITY=None, PLAYER2_TEAM_NICKNAME=None, PLAYER2_TEAM_ABBREVIATION=None, PERSON3TYPE=0, PLAYER3_ID=0, PLAYER3_NAME=None, PLAYER3_TEAM_ID=nan, PLAYER3_TEAM_CITY=None, PLAYER3_TEAM_NICKNAME=None, PLAYER3_TEAM_ABBREVIATION=None, VIDEO_AVAILABLE_FLAG=1)

In [8]:
df_dict={}
df= pd.DataFrame(columns=['game_id',
                          'home_team',
                          'away_team', 'date', 'fouls','dunks', '3pm', 'OT', 'clutch', 'performances'])

In [62]:
pbp[pbp["HOMEDESCRIPTION"].str.contains("Dunk", case=False, na=False) & ~pbp["HOMEDESCRIPTION"].str.contains("MISS", case=False, na=False) |
    pbp["VISITORDESCRIPTION"].str.contains("Dunk", case=False, na=False) & ~pbp["VISITORDESCRIPTION"].str.contains("MISS", case=False, na=False) ].shape[0]

pbp[pbp["PCTIMESTRING"].str.split(":").str[0].astype(int) <= 5]
pbp.dtypes

GAME_ID                       object
EVENTNUM                       int64
EVENTMSGTYPE                   int64
EVENTMSGACTIONTYPE             int64
PERIOD                         int64
WCTIMESTRING                  object
PCTIMESTRING                  object
HOMEDESCRIPTION               object
NEUTRALDESCRIPTION            object
VISITORDESCRIPTION            object
SCORE                         object
SCOREMARGIN                   object
PERSON1TYPE                    int64
PLAYER1_ID                     int64
PLAYER1_NAME                  object
PLAYER1_TEAM_ID              float64
PLAYER1_TEAM_CITY             object
PLAYER1_TEAM_NICKNAME         object
PLAYER1_TEAM_ABBREVIATION     object
PERSON2TYPE                    int64
PLAYER2_ID                     int64
PLAYER2_NAME                  object
PLAYER2_TEAM_ID              float64
PLAYER2_TEAM_CITY             object
PLAYER2_TEAM_NICKNAME         object
PLAYER2_TEAM_ABBREVIATION     object
PERSON3TYPE                    int64
PLAYER3_ID                     int64
PLAYER3_NAME                  object
PLAYER3_TEAM_ID              float64
PLAYER3_TEAM_CITY             object
PLAYER3_TEAM_NICKNAME         object
PLAYER3_TEAM_ABBREVIATION     object
VIDEO_AVAILABLE_FLAG           int64
dtype: object

In [163]:
def is_int_convertible(x):
    try:
        int(x)
        return True
    except (ValueError, TypeError):
        return False

In [185]:
pbp_valid= pbp[(pbp["PERIOD"]>=4) & (pbp["PCTIMESTRING"].str.split(":").str[0].astype(int) < 5) & (pbp['SCOREMARGIN'].notna()) & (pbp['SCOREMARGIN'].apply(is_int_convertible))]
clutch=(pbp_valid["SCOREMARGIN"].astype(int) <= 5) & (pbp_valid["SCOREMARGIN"].astype(int) >= -5)
clutch= 1 if True in clutch.unique() else 0
clutch

1

In [133]:
games[(games['TEAM_ABBREVIATION']=='DEN') & (games['PTS']==139)]

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
198,22024,1610612743,DEN,Denver Nuggets,0022401102,2025-04-01,DEN vs. MIN,L,289,139,...,0.75,8,37,45,33,7,7,16,22,-1.0
1480,22024,1610612743,DEN,Denver Nuggets,0022400461,2025-01-01,DEN vs. ATL,W,240,139,...,1.00,4,39,43,44,8,5,12,16,19.0

In [183]:
pbp = playbyplayv2.PlayByPlayV2("0022401102")
pbp = pbp.get_data_frames()[0]
pbp.iloc[404]

GAME_ID                                                             0022401102
EVENTNUM                                                                   589
EVENTMSGTYPE                                                                 1
EVENTMSGACTIONTYPE                                                          99
PERIOD                                                                       4
WCTIMESTRING                                                          12:21 AM
PCTIMESTRING                                                              4:41
HOMEDESCRIPTION              Westbrook 2' Cutting Finger Roll Layup Shot (8...
NEUTRALDESCRIPTION                                                        None
VISITORDESCRIPTION                                                        None
SCORE                                                                 99 - 106
SCOREMARGIN                                                                  7
PERSON1TYPE                                                                  4
PLAYER1_ID                                                              201566
PLAYER1_NAME                                                 Russell Westbrook
PLAYER1_TEAM_ID                                                   1610612743.0
PLAYER1_TEAM_CITY                                                       Denver
PLAYER1_TEAM_NICKNAME                                                  Nuggets
PLAYER1_TEAM_ABBREVIATION                                                  DEN
PERSON2TYPE                                                                  4
PLAYER2_ID                                                              203999
PLAYER2_NAME                                                      Nikola Jokić
PLAYER2_TEAM_ID                                                   1610612743.0
PLAYER2_TEAM_CITY                                                       Denver
PLAYER2_TEAM_NICKNAME                                                  Nuggets
PLAYER2_TEAM_ABBREVIATION                                                  DEN
PERSON3TYPE                                                                  0
PLAYER3_ID                                                                   0
PLAYER3_NAME                                                              None
PLAYER3_TEAM_ID                                                            NaN
PLAYER3_TEAM_CITY                                                         None
PLAYER3_TEAM_NICKNAME                                                     None
PLAYER3_TEAM_ABBREVIATION                                                 None
VIDEO_AVAILABLE_FLAG                                                         1
Name: 404, dtype: object

In [187]:
pbp['PERIOD'].unique()

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [143]:
ot = 1 if any(p in pbp['PERIOD'].unique() for p in [5, 6, 7]) else 0

In [191]:
games["TEAM_ABBREVIATION"].unique()

array(['ATL', 'BKN', 'UTA', 'MEM', 'ORL', 'OKC', 'SAC', 'MIL', 'NYK',
       'BOS', 'POR', 'DEN', 'WAS', 'GSW', 'HOU', 'NOP', 'PHI', 'LAC',
       'CHA', 'LAL', 'CLE', 'IND', 'TOR', 'PHX', 'SAS', 'MIN', 'DET',
       'CHI', 'MIA', 'DAL'], dtype=object)